version: '3.3'
services:
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
  db:
    image: library/mysql:5.7
    restart: always
    container_name: cardsagainsthumanity_db
    environment:
      MYSQL_ROOT_PASSWORD: 'cah_db_user@#!'
    ports:
      - 3306:3306
    volumes:
      - ../data:/var/lib/mysql
  cardsagainsthumanity:
    image: .
    restart: always
    container_name: cardsagainsthumanity
    ports:
      - 8080:8080

