FROM node:14 as build


COPY ./package-lock.json ./
COPY ./package.json ./
RUN npm ci

COPY ./src ./src
COPY ./lib ./lib
COPY ./babel.config.js ./
COPY ./webpack.config.js ./
COPY ./webpack.config.prod.js ./
RUN npm run build

FROM nginx
RUN apt-get update
COPY --from=build /srv/package/build /srv/package/cah
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
EXPOSE 443
